# app.yaml
runtime: python310
service: lechare-web-app
entrypoint: gunicorn -w 1 -k uvicorn.workers.UvicornWorker app.main:app --bind :$PORT

env_variables:
  DB_HOST: 186.202.152.70
  DB_NAME: queryanswer
  DB_USER: queryanswer
  DB_PASS: Esqueci#25